AWSTemplateFormatVersion: 2010-09-09
Description: "Deloy aws server"
Resource:
  ServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      - SecurityGroups:
          !Ref ServerInstanceSecGroup
        InstanceType: t2.micro
        ImageId: ami-08d4ac5b634553e16
        KeyName: udacity
  ServerInstanceSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngres:
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0


