
version: 2.1

commands:
  destroy-enviroment:
    steps:
      - run:
          name: Destroy enviroment
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Create ec2 server"
          command: |
            aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [12:a7:90:a2:03:c2:57:a6:28:79:2c:41:da:44:54:62]
      - run:
          name: Install ansible
          command: |
            apk add --update ansible
      - run: 
          name: Run ansible playbook to configure server
          command: |
            ansible-playbook -i inventory main.yml
  smoke-test:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Run smoke test
          command: return 1
      - destroy-enviroment





workflows:
  infrasructure-workflow:
    jobs:
      - create-infrastructure
      #- configure-infrastructure
      - smoke-test:
          requires:
            create-infrastructure

  
